Wrap response into error and result
manticoresoftware/manticoresearch-text-embeddings pull request #7
Opened 2024-10-18 08:10 UTC by donhardman

2024-10-18 08:51 UTC, klirichek commented on manticoresearch_text_embeddings.h
> +  void *model;
just to keep overall naming consistent:
`m_pModel` is more consistent in manticore style: m_ means 'member', p means 'pointer'

2024-10-18 08:51 UTC, klirichek commented on manticoresearch_text_embeddings.h
> +  char *error;
m.b. `const char *m_szError` ? 
We don't expect c++ side will modify pointee. And 'sz' common for asciiz strings

2024-10-18 08:51 UTC, klirichek commented on manticoresearch_text_embeddings.h
> +  FloatVec vector;
vector -> m_tData, or m_tEmbedding

2024-10-18 08:51 UTC, klirichek commented on manticoresearch_text_embeddings.h
> +  char *error;
m_szError (as above)

2024-10-18 08:51 UTC, klirichek commented on manticoresearch_text_embeddings.h
>    uintptr_t size;
here expected version tag.
size might be good when you constantly add new functions,
but actually that is version, or unique tag of the interface, that should be changed each time something published.

2024-10-28 05:41 UTC, sanikolaev requested changes

2024-10-28 05:41 UTC, sanikolaev commented on src/error.rs
> +			LibError::HuggingFaceApiBuildFailed => write!(f, "Failed to build Hugging Face API"),
This one looks confusing. Let's make it a little bit clearer.

2024-10-28 05:41 UTC, sanikolaev commented on src/error.rs
> +			LibError::ModelWeightsFetchFailed => write!(f, "Failed to load model weights"),
```suggestion
			LibError::ModelWeightsFetchFailed => write!(f, "Failed to download model weights"),
```

2024-10-28 05:41 UTC, sanikolaev commented on src/error.rs
> +			LibError::ModelWeightsLoadFailed => write!(f, "Failed to load model weights"),
```suggestion
			LibError::ModelWeightsLoadFailed => write!(f, "Failed to load model weights to memory"),
```

2024-10-28 05:41 UTC, sanikolaev commented on src/error.rs
> +			LibError::ModelTokenizerFetchFailed => write!(f, "Failed to load model tokenizer"),
```suggestion
			LibError::ModelTokenizerFetchFailed => write!(f, "Failed to download model tokenizer"),
```

2024-10-28 05:41 UTC, sanikolaev commented on src/error.rs
> +			LibError::ModelTokenizerLoadFailed => write!(f, "Failed to load model tokenizer"),
```suggestion
			LibError::ModelTokenizerLoadFailed => write!(f, "Failed to load model tokenizer to memory"),
```

2024-10-28 05:41 UTC, sanikolaev commented on src/error.rs
> +			LibError::ModelConfigFetchFailed => write!(f, "Failed to load model configuration"),
```suggestion
			LibError::ModelConfigFetchFailed => write!(f, "Failed to download model configuration"),
```

2024-10-28 05:41 UTC, sanikolaev commented on src/error.rs
> +			LibError::ModelLoadFailed => write!(f, "Failed to load model"),
```suggestion
			LibError::ModelLoadFailed => write!(f, "Failed to load model to memory"),
```

2024-10-28 08:24 UTC, merged